package com.przemo.projectmanagementweb.domain;
// Generated 2016-05-05 17:32:58 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Projects generated by hbm2java
 */
public class Projects  implements java.io.Serializable {


     private int id;
     private Users users;
     private String name;
     private String description;
     private Date startdate;
     private Date enddate;
     private Set tasks = new HashSet(0);

    public Projects() {
    }

	
    public Projects(int id, String name, Date startdate) {
        this.id = id;
        this.name = name;
        this.startdate = startdate;
    }
    public Projects(int id, Users users, String name, String description, Date startdate, Date enddate, Set tasks) {
       this.id = id;
       this.users = users;
       this.name = name;
       this.description = description;
       this.startdate = startdate;
       this.enddate = enddate;
       this.tasks = tasks;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
    public Set getTasks() {
        return this.tasks;
    }
    
    public void setTasks(Set tasks) {
        this.tasks = tasks;
    }




}


