package com.przemo.projectmanagementweb.domain;
// Generated 2016-08-22 15:22:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sprint generated by hbm2java
 */
public class Sprint  implements java.io.Serializable {


     private int id;
     private SprintStatus sprintStatus;
     private String name;
     private Date startDate;
     private Date endDate;
     private int timeAvailable;
     private Set tasks = new HashSet(0);

    public Sprint() {
    }

	
    public Sprint(int id, String name, Date startDate, Date endDate, int timeAvailable) {
        this.id = id;
        this.name = name;
        this.startDate = startDate;
        this.endDate = endDate;
        this.timeAvailable = timeAvailable;
    }
    public Sprint(int id, SprintStatus sprintStatus, String name, Date startDate, Date endDate, int timeAvailable, Set tasks) {
       this.id = id;
       this.sprintStatus = sprintStatus;
       this.name = name;
       this.startDate = startDate;
       this.endDate = endDate;
       this.timeAvailable = timeAvailable;
       this.tasks = tasks;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public SprintStatus getSprintStatus() {
        return this.sprintStatus;
    }
    
    public void setSprintStatus(SprintStatus sprintStatus) {
        this.sprintStatus = sprintStatus;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public int getTimeAvailable() {
        return this.timeAvailable;
    }
    
    public void setTimeAvailable(int timeAvailable) {
        this.timeAvailable = timeAvailable;
    }
    public Set getTasks() {
        return this.tasks;
    }
    
    public void setTasks(Set tasks) {
        this.tasks = tasks;
    }




}


