package com.przemo.projectmanagementweb.domain;
// Generated 2016-05-05 17:32:58 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TaskComments generated by hbm2java
 */
public class TaskComments  implements java.io.Serializable {


     private int id;
     private Users users;
     private int task;
     private Date date;
     private String comment;

    public TaskComments() {
    }

	
    public TaskComments(int id, Users users, int task, Date date) {
        this.id = id;
        this.users = users;
        this.task = task;
        this.date = date;
    }
    public TaskComments(int id, Users users, int task, Date date, String comment) {
       this.id = id;
       this.users = users;
       this.task = task;
       this.date = date;
       this.comment = comment;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public int getTask() {
        return this.task;
    }
    
    public void setTask(int task) {
        this.task = task;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


