package com.przemo.projectmanagementweb.domain;
// Generated 2016-05-05 17:32:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TaskType generated by hbm2java
 */
public class TaskType  implements java.io.Serializable {


     private int id;
     private String name;
     private Set tasks = new HashSet(0);

    public TaskType() {
    }

	
    public TaskType(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public TaskType(int id, String name, Set tasks) {
       this.id = id;
       this.name = name;
       this.tasks = tasks;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getTasks() {
        return this.tasks;
    }
    
    public void setTasks(Set tasks) {
        this.tasks = tasks;
    }




}


