package com.przemo.projectmanagementweb.domain;
// Generated 2016-04-20 12:30:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Task generated by hbm2java
 */
public class Task  implements java.io.Serializable {


     private int id;
     private Sprint sprint;
     private Status status;
     private TaskType taskType;
     private Users users;
     private String title;
     private String description;
     private Integer estimatedTime;
     private Integer realTime;
     private Set timeLogs = new HashSet(0);
     private Set taskCommentses = new HashSet(0);

    public Task() {
    }

	
    public Task(int id, Sprint sprint, Status status, TaskType taskType, Users users, String title) {
        this.id = id;
        this.sprint = sprint;
        this.status = status;
        this.taskType = taskType;
        this.users = users;
        this.title = title;
    }
    public Task(int id, Sprint sprint, Status status, TaskType taskType, Users users, String title, String description, Integer estimatedTime, Integer realTime, Set timeLogs, Set taskCommentses) {
       this.id = id;
       this.sprint = sprint;
       this.status = status;
       this.taskType = taskType;
       this.users = users;
       this.title = title;
       this.description = description;
       this.estimatedTime = estimatedTime;
       this.realTime = realTime;
       this.timeLogs = timeLogs;
       this.taskCommentses = taskCommentses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Sprint getSprint() {
        return this.sprint;
    }
    
    public void setSprint(Sprint sprint) {
        this.sprint = sprint;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public TaskType getTaskType() {
        return this.taskType;
    }
    
    public void setTaskType(TaskType taskType) {
        this.taskType = taskType;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getEstimatedTime() {
        return this.estimatedTime;
    }
    
    public void setEstimatedTime(Integer estimatedTime) {
        this.estimatedTime = estimatedTime;
    }
    public Integer getRealTime() {
        return this.realTime;
    }
    
    public void setRealTime(Integer realTime) {
        this.realTime = realTime;
    }
    public Set getTimeLogs() {
        return this.timeLogs;
    }
    
    public void setTimeLogs(Set timeLogs) {
        this.timeLogs = timeLogs;
    }
    public Set getTaskCommentses() {
        return this.taskCommentses;
    }
    
    public void setTaskCommentses(Set taskCommentses) {
        this.taskCommentses = taskCommentses;
    }




}


