package com.przemo.projectmanagementweb.domain;
// Generated 2016-05-05 17:32:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int id;
     private Role role;
     private String email;
     private Set taskCommentses = new HashSet(0);
     private Set projectses = new HashSet(0);
     private Set tasks = new HashSet(0);

    public Users() {
    }

	
    public Users(int id) {
        this.id = id;
    }
    public Users(int id, Role role, String email, Set taskCommentses, Set projectses, Set tasks) {
       this.id = id;
       this.role = role;
       this.email = email;
       this.taskCommentses = taskCommentses;
       this.projectses = projectses;
       this.tasks = tasks;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getTaskCommentses() {
        return this.taskCommentses;
    }
    
    public void setTaskCommentses(Set taskCommentses) {
        this.taskCommentses = taskCommentses;
    }
    public Set getProjectses() {
        return this.projectses;
    }
    
    public void setProjectses(Set projectses) {
        this.projectses = projectses;
    }
    public Set getTasks() {
        return this.tasks;
    }
    
    public void setTasks(Set tasks) {
        this.tasks = tasks;
    }




}


